version: '3.4'

services:

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - LANG=C.UTF-8
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - backend-network
        restart: always
    
    phpmyadmin:
        image: phpmyadmin:5.1
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        networks:
            - frontend-network
            - backend-network
        depends_on: 
            - mysql
        restart: always

    apache:
        build: ./apache
        networks:
            - frontend-network
            - backend-network
        depends_on: 
            - mysql
        restart: always
        volumes:
            - ./src:/var/www/html/

    https-portal:
        image: steveltn/https-portal:1
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            DOMAINS: 'practicahttps.ml -> http://apache:80'
        # STAGE: 'production' # Don't use production until staging works
        # FORCE_RENEW: 'true'
        networks:
            - frontend-network

networks:
    frontend-network:
    backend-network:

volumes:
    mysql_data: