FROM ubuntu:focal

LABEL title="apache-lamp" \
  author="Jacobo Azmani"

ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=Europe/Madrid

RUN apt-get update \
    && apt-get install -y apache2 \
    && apt-get install -y php \
    && apt-get install -y libapache2-mod-php \
    && apt-get install -y php-mysql

#RUN apt install git -y \
#    && cd /tmp \
#    && git clone https://github.com/jacobo87/Proyecto_ASIR\
#    && mv /tmp/Proyecto_ASIR/src/* /var/www/html/ \
#    && sed -i 's/localhost/mysql/' /var/www/html/src/configuracion/conexion.php \
#    && rm /var/www/html/index.html

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"] 